// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmd1RwVbB2_RIAIBY0Eo7waQ1EN24IhSo',
    appId: '1:185126489955:web:36e173dbb743a5a4048d56',
    messagingSenderId: '185126489955',
    projectId: 'resturant-review-app-c42e0',
    authDomain: 'resturant-review-app-c42e0.firebaseapp.com',
    databaseURL: 'https://resturant-review-app-c42e0-default-rtdb.firebaseio.com',
    storageBucket: 'resturant-review-app-c42e0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWku1NtuMJirLJHs2qvqHqctCHOZ0pjrk',
    appId: '1:185126489955:android:57b861b3a1d332b4048d56',
    messagingSenderId: '185126489955',
    projectId: 'resturant-review-app-c42e0',
    databaseURL: 'https://resturant-review-app-c42e0-default-rtdb.firebaseio.com',
    storageBucket: 'resturant-review-app-c42e0.firebasestorage.app',
  );
}
